### ISSUE TITLE
 Failed to open zarr store.

### ISSUE THREAD

**Issue by lamaliang** [NCAR/cesm2-le-aws#10]
Hello 

Today, I would like re-calculus some value, but there are some error information as following :

OSError: 
            Failed to open zarr store.

            *** Arguments passed to xarray.open_zarr() ***:

            - store: <fsspec.mapping.FSMap object at 0x7f118c3641d0>
            - kwargs: {}

            *** fsspec options used ***:

            - root: ncar-cesm2-lens/atm/daily/cesm2LE-ssp370-smbb-TREFHT.zarr
            - protocol: ('s3', 's3a')

**Comment by mgrover1** [comment]
You need to specify anonymous access - the examples `storage_options` argument upon reading in the data. 

If you are reading from the catalog, use the following:

```python
dsets = catalog_subset.to_dataset_dict(storage_options={'anon':True})
```

if you are using `xarray.open_zarr()` directly, you need to include the same argument

```python
ds = xr.open_zarr('s3://ncar-cesm2-lens/atm/daily/cesm2LE-ssp370-smbb-TREFHT.zarr',
                  storage_options={'anon':True})
```

**Comment by lamaliang** [comment]
OK! It is my mistake. Thank you so much.

This is my first time to use zarr+intake+xarray to read the data. 

I am very grateful for your patience.

**Comment by mgrover1** [comment]
Glad it worked! Thanks for raising questions/issues! The feedback is greatly appreciated 😁
