### ISSUE TITLE
not found variable - PS

### ISSUE THREAD

**Issue by lamaliang** [NCAR/cesm2-le-aws#8]
Hello 

I would like to convert veritcal coordinate from hybrid sigma level to pressure level. But in zarr coordinate variables, I didn't found the variable PS. Could you help me? Please 

Thank you so much.

**Comment by mgrover1** [comment]
I can make sure that those are added! Thanks for letting us know.

**Comment by lamaliang** [comment]
Thank you so much.

**Comment by lamaliang** [comment]
BTW, I saw you upload the new variables include PS, thank you so much. But, could you upload daily output PS to AWS, thanks.

**Comment by mgrover1** [comment]
The daily `PS` data have been added as well! The catalog has been updated accordingly.

**Comment by lamaliang** [comment]
Thank you so much. BTW, could you upload V variable for daily output?

**Comment by mgrover1** [comment]
This variable is now included on AWS/the catalog

**Comment by lamaliang** [comment]
GOOD! Thanks.
