### ISSUE TITLE
Check aws-cesm2-le.json

### ISSUE THREAD

**Issue by lamaliang** [NCAR/cesm2-le-aws#9]
Hello

yesterday I can read the aws-cesm2-le.json, but today there is a error message as following as following :
"The data in the forcing_variant column should either be all NaN or there should be no NaNs"

Please help me, thank you so much.

**Comment by mgrover1** [comment]
Good catch - I added the required `forcing_variant` values for the static (grid) stores... this solved the issue!

**Comment by lamaliang** [comment]
Thank you so much.
